### ISSUE TITLE
when ever i drag the file to cmd is just opens and then closes it doesnt work

### ISSUE THREAD

**Issue by brisk1987** [ixEcIipse/RoConsole#1]

**Comment by ixEcIipse** [comment]
try left clicking on the folder holding the python script and click "open terminal here" then try, or you can follow this tutorial 

https://www.youtube.com/watch?v=Shf5m_Uol9g

**Comment by brisk1987** [comment]
> try left clicking on the folder holding the python script and click "open terminal here" then try, or you can follow this tutorial
> 
> https://www.youtube.com/watch?v=Shf5m_Uol9g
now it says
ERROR: Could not find a version that satisfies the requirement admcheck (from versions: none)
ERROR: No matching distribution found for admcheck
finished installing required packages please restart terminal.
Traceback (most recent call last): 
and it says
ModuleNotFoundError: No module named 'colorama' 
How do i fix this?

**Comment by ixEcIipse** [comment]
alr i should of fixed the python script give it a retry
